databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    region: oregon
    name: mysite
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: FRONTEND_ORIGIN
        value: https://map-survey-app.onrender.com